version: "3"
services:
  postgres:
    container_name: "dropbox_postgresql"
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - '/var/lib/postgresql/data:/var/lib/postgresql/data'
