version: "2"
services:
  dropbox:
    container_name: "dropbox-application"
    image: dchristofolli/dropbox
    ports:
      - '8080:8080'
    depends_on:
      - mongo-express
  mongo:
    container_name: "dropbox-mongo"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './mongo-data:/data/db'

  mongo-express:
    container_name: "dropbox-mongoe"
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
  
